Organizations:
    - &OrgXXX
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: OrgXXXMSP

        # ID to load the MSP definition as
        ID: OrgXXXMSP

        MSPDir: ../organizations/peerOrganizations/orgXXX.example.com/msp

        Policies:
            Readers:
                Type: Signature
                Rule: "OR('OrgXXXMSP.admin', 'OrgXXXMSP.peer', 'OrgXXXMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('OrgXXXMSP.admin', 'OrgXXXMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('OrgXXXMSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('OrgXXXMSP.peer')"

        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
            - Host: peer0.orgXXX.example.com
              Port: YYY
